Implement GET endpoint for GenericSensors Interface
UBCSailbot/website pull request #57
Opened 2023-11-08 09:25 UTC by dk1702

### Description

- Resolves #48 

### Verification

- [ ] 

### Resources

-

2023-11-09 01:03 UTC, jahn18 requested changes
Please also change the api name to `generic-sensors` (add a dash)

2023-11-09 04:34 UTC, dk1702 commented on models/helper/parser.ts
> +        prev[i] = v.toString();
done

2023-11-09 04:38 UTC, dk1702 commented on tests/steps/given.ts
> +      }
done

2023-11-11 01:58 UTC, jahn18 commented on tests/features/genericsensors.feature
> +@genericsensors
As discussed on slack, please add a dash to the tag

2023-11-11 20:09 UTC, jahn18 approved these changes

2023-11-11 20:09 UTC, merged